config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :enrollments
  root to: 'pages#home'
  devise_for :users
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord

    has_many :enrollments, dependent: :destroy
    has_many :users, through: :enrollments

    #def self.import(file)
        #CSV.foreach(file.path, headers: true) do |row|
            #Course.create! row.to_hash
        #end
    #end
    
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user

  after_save :update_student

  def update_student
    UpdateStudentsProgressWorker.perform_async(self.user_id)
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :enrollments, dependent: :destroy
  has_many :courses, through: :enrollments
  has_one :student
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    
      #file = Dir.glob("/xchool/public/courses.csv") #=> This folder directory where read the CSV files
      #file.each do |file|
          #Course.import(file)
      #end
      
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end 
    
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title)
    end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]
  before_action :authenticate_admin

  # GET /enrollments or /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = Enrollment.create(enrollment_params)

    
    # byebug
    # @course = params[:course_id]
    # if CreateEnrollment.call(@course, current_user, flash)
    #     redirect_to course_path(@course)
    # end
    # @enrollment.user = current_user 
    


    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully created." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:course_id, :user_id, :pass_score, :progress, :score, :completed, :graduate)
    end

    def authenticate_admin
      return unless !current_user.admin
      redirect_to root_path, alert: 'Page not found'
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    #@admin_signed_in = current_user.admin
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:user_id, :average_score, :average_progress, :graduated)
    end

    def authenticate_admin
      return unless !current_user.admin
      redirect_to root_path, alert: 'Page not found'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p>
    <strong>Title:</strong>
    <%= course.title %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Courses</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Course ID</th>
      <th scope="col">Title</th>
    </tr>
  </thead>
  <tbody>
  <% @courses.each do |course| %>
    <tr>
      <th scope="row">1</th>
      <td><%= course.id %></td>
      <td><%= course.title %></td>
      <td><%= link_to "Show this course", course %>
      <td><%= link_to "Edit", edit_course_path(course) %></td>
      <td><%= link_to "Destroy", course, method: :delete,data: {confirm: 'Are you sure'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "New course", new_course_path %>
      

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>

<% provide(:button_text, 'Apply') %>
<%= render @course %>

<div>
  <%= link_to "Edit this course", edit_course_path(@course) %> |
  <%= link_to "Back to courses", courses_path %>

  <%= button_to "Destroy this course", @course, method: :delete %>
</div>

app/views/enrollments/_enrollment.html.erb
<div id="<%= dom_id enrollment %>">
  <p>
    <strong>Course:</strong>
    <%= enrollment.course_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= enrollment.user_id %>
  </p>

  <p>
    <strong>Pass score:</strong>
    <%= enrollment.pass_score %>
  </p>

  <p>
    <strong>Progress:</strong>
    <%= enrollment.progress %>
  </p>

  <p>
    <strong>Score:</strong>
    <%= enrollment.score %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= enrollment.completed %>
  </p>

  <p>
    <strong>Graduate:</strong>
    <%= enrollment.graduate %>
  </p>

</div>

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment) do |form| %>
  <% if enrollment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
        <% enrollment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.text_field :course_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :pass_score, style: "display: block" %>
    <%= form.number_field :pass_score %>
  </div>

  <div>
    <%= form.label :progress, style: "display: block" %>
    <%= form.number_field :progress %>
  </div>

  <div>
    <%= form.label :score, style: "display: block" %>
    <%= form.number_field :score %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.label :graduate, style: "display: block" %>
    <%= form.check_box :graduate %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Show this enrollment", @enrollment %> |
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Enrollments</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Course ID</th>
      <th scope="col">User ID</th>
      <th scope="col">Pass score</th>
      <th scope="col">Progress</th>
      <th scope="col">Score</th>
      <th scope="col">Completed</th>
      <th scope="col">Graduate</th>
    </tr>
  </thead>
  <tbody>
  <% @enrollments.each do |enrollment| %>
    <tr>
      <th scope="row">1</th>
      <td><%= enrollment.course_id %></td>
      <td><%= enrollment.user_id %></td>
      <td><%= enrollment.pass_score %></td>
      <td><%= enrollment.progress %></td>
      <td><%= enrollment.score %></td>
      <td><%= enrollment.completed %></td>
      <td><%= enrollment.graduate %></td>
      <td><%= link_to "Show this enrollment", enrollment %>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "New enrollment", new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @enrollment %>

<div>
  <%= link_to "Edit this enrollment", edit_enrollment_path(@enrollment) %> |
  <%= link_to "Back to enrollments", enrollments_path %>

  <%= button_to "Destroy this enrollment", @enrollment, method: :delete %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
  <%= link_to "Xchool", root_path, id: "logo" %>
<nav>
    <ul class="nav navbar-nav navbar-right">
      <li><h3><%= link_to "Home", root_path %></h3></li>

        <% if current_user  %>
            <li><h3> <%= link_to 'Sign out', destroy_user_session_path, 'data-turbo-method': :delete  %></h3></li>
            <li><h3><%= link_to 'Courses', courses_path %></h3></li>
            <% if current_user.admin %>
                <li><h3><%= link_to 'Enrollments', enrollments_path %></h3></li>
                <li><h3><%= link_to 'Students', students_path %></h3></li>
            <% end %>
        <% else %>
            <li><h3><%= link_to 'Sign up', new_user_registration_path %></h3></li>
            <li><h3><%= link_to 'Sign in', new_user_session_path %></h3></li>
            <li><h3><%= link_to 'Courses', courses_path %></h3></li>   
        <% end %>
    </ul>
  </nav>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xchool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/header'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome!</h1> 
<img src="/images/xchoolimg.jpg" alt="rss feed" />

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :average_score, style: "display: block" %>
    <%= form.number_field :average_score %>
  </div>

  <div>
    <%= form.label :average_progress, style: "display: block" %>
    <%= form.number_field :average_progress %>
  </div>

  <div>
    <%= form.label :graduated, style: "display: block" %>
    <%= form.check_box :graduated %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>User:</strong>
    <%= student.user_id %>
  </p>

  <p>
    <strong>Average score:</strong>
    <%= student.average_score %>
  </p>

  <p>
    <strong>Average progress:</strong>
    <%= student.average_progress %>
  </p>

  <p>
    <strong>Graduated:</strong>
    <%= student.graduated %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">User ID</th>
      <th scope="col">Average Score</th>
      <th scope="col">Average progress</th>
      <th scope="col">Graduated</th>
    </tr>
  </thead>
  <tbody>
  <% @students.each do |student| %>
    <tr>
      <th scope="row">1</th>
      <td><%= student.user_id %></td>
      <td><%= student.average_score %></td>
      <td><%= student.average_progress %></td>
      <td><%= student.graduated %></td>
      <td><%= link_to "Show this student", student %>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>

app/views/users/show.html.erb
<h1><%= @user.email%>'s Page</h1>

<h2>Courses</h2>
<%= button_to "Register Course", new_enrollment_path, method: :get%>
<ul>
    <%@user.enrollments.each do |enrollment|%>
        <li><%= enrollment.course.title%></li>
        <%= button_to "Drop Enrollment", enrollment_path(enrollment), method: :delete%>
    <%end%>
</ul>

<%= button_to "Edit user", edit_user_path, method: :get%>
<%= button_to "Destroy user", user_path, method: :delete%>
<%= link_to "Destroy user", user_path%>